"""User model mapped to Better Auth user table."""
from datetime import datetime
from typing import Optional
from uuid import UUID

from pydantic import field_validator, EmailStr
from sqlmodel import Field, SQLModel, Column
from sqlalchemy import DateTime


class User(SQLModel, table=True):
    """
    User model mapped to Better Auth user table.

    Better Auth manages authentication and uses String IDs internally.
    We've extended the schema with a UUID column for type consistency
    across our application's API routes and foreign key relationships.
    """

    __tablename__ = "user"  # Better Auth table name (singular, no 's')

    # Better Auth fields (required for Better Auth compatibility)
    id: str = Field(primary_key=True)  # Better Auth String ID
    email: str = Field(unique=True, index=True, max_length=255)
    emailVerified: bool = Field(default=False)
    name: Optional[str] = Field(default=None, max_length=255)
    image: Optional[str] = Field(default=None)
    createdAt: datetime = Field(
        default_factory=lambda: datetime.utcnow(),
        sa_column=Column(DateTime(timezone=False), nullable=False)
    )
    updatedAt: datetime = Field(
        default_factory=lambda: datetime.utcnow(),
        sa_column=Column(DateTime(timezone=False), nullable=False)
    )

    # Our application field (for type consistency across API routes)
    uuid: UUID = Field(unique=True, index=True, nullable=False)

    # Note: Password is stored in Better Auth's 'account' table, not here


class UserResponse(SQLModel):
    """
    Schema for user data in API responses.

    Uses UUID instead of Better Auth's String ID for consistency
    with our application's API routes.
    """
    uuid: UUID  # Use UUID in API responses
    email: str
    name: Optional[str]
    createdAt: datetime
    updatedAt: datetime

    model_config = {"from_attributes": True}

    @field_validator("email", mode="before")
    @classmethod
    def normalize_email(cls, v: str) -> str:
        """Normalize email to lowercase."""
        if isinstance(v, str):
            return v.lower().strip()
        return v


# Removed schemas (Better Auth handles these on frontend):
# - UserCreate (registration handled by Better Auth)
# - UserLogin (login handled by Better Auth)
# - UserWithToken (JWT tokens generated by Better Auth)
# - UserBase (not needed with Better Auth schema)
