"""create tasks table with indexes and constraints

Revision ID: 3f7554956f5b
Revises: 001
Create Date: 2025-12-29 20:09:43.079044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f7554956f5b'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_pattern', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('recurrence_config', sa.JSON(), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high') OR priority IS NULL", name='check_priority_enum'),
    sa.CheckConstraint("recurrence_pattern IN ('daily', 'weekly', 'monthly', 'custom') OR recurrence_pattern IS NULL", name='check_recurrence_pattern_enum'),
    sa.CheckConstraint('length(description) <= 10000', name='check_description_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_due_reminders', 'tasks', ['due_date', 'reminder_at'], unique=False, postgresql_where=sa.text('completed = FALSE AND deleted_at IS NULL'))
    op.create_index('idx_tasks_user_completed', 'tasks', ['user_id', 'completed'], unique=False)
    op.create_index('idx_tasks_user_due_date', 'tasks', ['user_id', 'due_date'], unique=False, postgresql_where=sa.text('due_date IS NOT NULL'))
    op.create_index('idx_tasks_user_priority', 'tasks', ['user_id', 'priority'], unique=False, postgresql_where=sa.text('priority IS NOT NULL'))
    op.create_index(op.f('ix_tasks_completed'), 'tasks', ['completed'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks', if_exists=True)
    op.drop_index(op.f('ix_tasks_completed'), table_name='tasks', if_exists=True)
    op.drop_index('idx_tasks_user_priority', table_name='tasks', postgresql_where=sa.text('priority IS NOT NULL'), if_exists=True)
    op.drop_index('idx_tasks_user_due_date', table_name='tasks', postgresql_where=sa.text('due_date IS NOT NULL'), if_exists=True)
    op.drop_index('idx_tasks_user_completed', table_name='tasks', if_exists=True)
    op.drop_index('idx_tasks_due_reminders', table_name='tasks', postgresql_where=sa.text('completed = FALSE AND deleted_at IS NULL'), if_exists=True)
    op.drop_table('tasks', if_exists=True)
    # ### end Alembic commands ###
