"""create notifications table with indexes and constraints

Revision ID: 60b6220ba320
Revises: 8be71e35d938
Create Date: 2025-12-29 20:55:13.885430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60b6220ba320'
down_revision: Union[str, None] = '8be71e35d938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    # sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    # sa.Column('id', sa.Uuid(), nullable=False),
    # sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_table('tags',
    # sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.Uuid(), nullable=False),
    # sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    # sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    # sa.CheckConstraint("color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'", name='check_color_hex_format'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index('idx_tags_user_id', 'tags', ['user_id'], unique=False)
    # op.create_index('idx_tags_user_name_unique', 'tags', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    # op.create_table('tasks',
    # sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.Uuid(), nullable=False),
    # sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('completed', sa.Boolean(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    # sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('recurrence_pattern', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    # sa.Column('recurrence_config', sa.JSON(), nullable=True),
    # sa.CheckConstraint("priority IN ('low', 'medium', 'high') OR priority IS NULL", name='check_priority_enum'),
    # sa.CheckConstraint("recurrence_pattern IN ('daily', 'weekly', 'monthly', 'custom') OR recurrence_pattern IS NULL", name='check_recurrence_pattern_enum'),
    # sa.CheckConstraint('length(description) <= 10000', name='check_description_length'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index('idx_tasks_due_reminders', 'tasks', ['due_date', 'reminder_at'], unique=False, postgresql_where=sa.text('completed = FALSE AND deleted_at IS NULL'))
    # op.create_index('idx_tasks_user_completed', 'tasks', ['user_id', 'completed'], unique=False)
    # op.create_index('idx_tasks_user_due_date', 'tasks', ['user_id', 'due_date'], unique=False, postgresql_where=sa.text('due_date IS NOT NULL'))
    # op.create_index('idx_tasks_user_priority', 'tasks', ['user_id', 'priority'], unique=False, postgresql_where=sa.text('priority IS NOT NULL'))
    # op.create_index(op.f('ix_tasks_completed'), 'tasks', ['completed'], unique=False)
    # op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('email', 'push', 'sms', 'webhook')", name='check_notification_channel_enum'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed')", name='check_notification_status_enum'),
    sa.CheckConstraint("type IN ('task_reminder', 'task_due', 'task_overdue', 'task_completed', 'system')", name='check_notification_type_enum'),
    sa.CheckConstraint('length(body) <= 10000', name='check_notification_body_length'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_pending', 'notifications', ['user_id', 'status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('idx_notifications_task_id', 'notifications', ['task_id'], unique=False, postgresql_where=sa.text('task_id IS NOT NULL'))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # op.create_table('task_tags',
    # sa.Column('task_id', sa.BigInteger(), nullable=False),
    # sa.Column('tag_id', sa.BigInteger(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('task_id', 'tag_id')
    # )
    # op.create_index('idx_task_tags_tag_id', 'task_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_task_tags_tag_id', table_name='task_tags')
    # op.drop_table('task_tags')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications', if_exists=True)
    op.drop_index('idx_notifications_task_id', table_name='notifications', postgresql_where=sa.text('task_id IS NOT NULL'), if_exists=True)
    op.drop_index('idx_notifications_pending', table_name='notifications', postgresql_where=sa.text("status = 'pending'"), if_exists=True)
    op.drop_table('notifications', if_exists=True)
    # op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    # op.drop_index(op.f('ix_tasks_completed'), table_name='tasks')
    # op.drop_index('idx_tasks_user_priority', table_name='tasks', postgresql_where=sa.text('priority IS NOT NULL'))
    # op.drop_index('idx_tasks_user_due_date', table_name='tasks', postgresql_where=sa.text('due_date IS NOT NULL'))
    # op.drop_index('idx_tasks_user_completed', table_name='tasks')
    # op.drop_index('idx_tasks_due_reminders', table_name='tasks', postgresql_where=sa.text('completed = FALSE AND deleted_at IS NULL'))
    # op.drop_table('tasks')
    # op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    # op.drop_index('idx_tags_user_name_unique', table_name='tags', postgresql_where=sa.text('deleted_at IS NULL'))
    # op.drop_index('idx_tags_user_id', table_name='tags')
    # op.drop_table('tags')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.drop_table('users')
    # ### end Alembic commands ###
