"""Skill-Aware Trader - Agent that uses learned skills from Observer Agent.

This agent extends the agentic trader to include skills consumption,
allowing it to benefit from institutional knowledge accumulated over
time by the Observer Agent.
"""

from __future__ import annotations

from typing import Any, Optional

from langchain_anthropic import ChatAnthropic

from agent_arena.agentic.base import AgenticTrader
from agent_arena.agentic.graph import create_trading_graph
from agent_arena.agentic.tools.skills import SkillRecommendationTool, TradingSkillsTool
from agent_arena.core.models import Decision


class SkillAwareTrader(AgenticTrader):
    """
    Trading agent that leverages learned skills.

    This agent extends AgenticTrader with:
    1. Access to skills generated by Observer Agent
    2. Skill-aware system prompt
    3. Tools for querying and applying skills

    The agent will automatically consult relevant skills before
    making trading decisions, applying institutional knowledge
    from past competition analysis.

    Example config:
        config:
            model: claude-sonnet-4-20250514
            max_iterations: 4
            skills_dir: ".claude/skills"
            always_check_skills: true
            character: "A disciplined trader who learns from history"
    """

    def __init__(self, agent_id: str, name: str, config: Optional[dict] = None):
        super().__init__(agent_id, name, config)
        config = config or {}

        # Use Sonnet by default for skill-aware agent (needs reasoning for skill application)
        self.model = config.get("model", "claude-sonnet-4-20250514")
        self.max_iterations = config.get("max_iterations", 4)

        # Skills configuration
        self.skills_dir = config.get("skills_dir", ".claude/skills")
        self.always_check_skills = config.get("always_check_skills", True)

        # Initialize skills tools
        self._skills_tool = TradingSkillsTool(skills_dir=self.skills_dir)
        self._skill_recommend_tool = SkillRecommendationTool(skills_tool=self._skills_tool)

        # Add skills tools to the tool list (inherited tools + skills)
        self.tools.extend([
            self._skills_tool,
            self._skill_recommend_tool,
        ])

    async def on_start(self) -> None:
        """Initialize LLM and graph with skill-aware system prompt."""
        # Create LLM with tools bound
        self._llm = ChatAnthropic(
            model=self.model,
            temperature=self.temperature,
            max_tokens=2048,  # Larger for skill content
        ).bind_tools(self.tools)

        # Create the trading graph with skill-aware prompt
        self._graph = create_trading_graph(
            llm=self._llm,
            tools=self.tools,
            memory_store=self._memory_store,
            system_prompt=self._build_skill_aware_prompt(),
        )

    def _build_skill_aware_prompt(self) -> str:
        """Build system prompt that emphasizes skill usage."""
        # Check what skills are available
        available_skills = self._skills_tool._get_available_skills()
        skills_list = ", ".join(available_skills) if available_skills else "none yet"

        return f"""You are a sophisticated trading agent with access to LEARNED SKILLS.

Unlike basic traders, you can access institutional knowledge accumulated from
analyzing past competition data. This knowledge is stored in skills that you
should consult before making decisions.

AVAILABLE SKILLS: {skills_list}

HOW TO USE SKILLS:
1. Use `trading_skills` tool to read skill content
2. Use `recommend_skill` tool if unsure which skill is relevant
3. Apply the guidance from skills to your decision-making
4. Document which skills influenced your decision

DECISION WORKFLOW:
1. **Assess situation**: Analyze market data, portfolio state
2. **Consult skills**: {"ALWAYS check" if self.always_check_skills else "Check when relevant"}
   - For market analysis → check `market-regimes`
   - For position sizing → check `risk-management`
   - For general guidance → check `trading-wisdom`
3. **Apply tools**: Use technical analysis, risk calculator, etc.
4. **Make decision**: Combine skill guidance with current analysis

SKILL PRIORITY:
- Skills represent STATISTICAL EVIDENCE from real competition data
- Higher confidence skills should carry more weight
- If skill guidance conflicts with your analysis, note this in reasoning
- When in doubt, follow high-confidence skill rules

CHARACTER:
{self.character or "A disciplined trader who respects historical evidence."}

Remember: Those who don't learn from history are doomed to repeat it.
Use your skills to avoid past mistakes and replicate past successes."""

    async def decide(self, context: dict) -> Decision:
        """Make a skill-informed trading decision."""
        # Ensure graph is created
        if self._graph is None:
            await self.on_start()

        # Get decision from parent class
        decision = await super().decide(context)

        # Add skill-aware metadata
        decision.metadata["skill_aware"] = True
        decision.metadata["skills_available"] = self._skills_tool._get_available_skills()

        # Check if skills were used (look in tool results)
        # This helps track skill adoption
        tool_calls = decision.metadata.get("thoughts", [])
        skills_consulted = []
        for thought in tool_calls:
            if isinstance(thought, str):
                if "trading_skills" in thought.lower():
                    skills_consulted.append("trading_skills")
                if "recommend_skill" in thought.lower():
                    skills_consulted.append("recommend_skill")
        decision.metadata["skills_consulted"] = skills_consulted

        return decision


class SkillOnlyTrader(SkillAwareTrader):
    """
    Minimal trader that ONLY uses skills, no other tools.

    This agent demonstrates pure skill-based trading without
    technical analysis tools. Useful for testing skill effectiveness.

    The agent can only:
    1. Read skills
    2. Get skill recommendations
    3. Make decisions based on skill guidance

    Example config:
        config:
            model: claude-haiku-4-5-20251001  # Can use cheaper model
            max_iterations: 2
            skills_dir: ".claude/skills"
    """

    def __init__(self, agent_id: str, name: str, config: Optional[dict] = None):
        # Skip AgenticTrader init, go to BaseAgent
        from agent_arena.core.agent import BaseAgent
        BaseAgent.__init__(self, agent_id, name, config)

        config = config or {}
        self.model = config.get("model", "claude-haiku-4-5-20251001")
        self.max_iterations = config.get("max_iterations", 2)
        self.temperature = config.get("temperature", 0.5)
        self.character = config.get("character", "")
        self.skills_dir = config.get("skills_dir", ".claude/skills")
        self.always_check_skills = True

        # ONLY skills tools, nothing else
        self._skills_tool = TradingSkillsTool(skills_dir=self.skills_dir)
        self._skill_recommend_tool = SkillRecommendationTool(skills_tool=self._skills_tool)
        self.tools = [self._skills_tool, self._skill_recommend_tool]

        # Graph components
        self._graph = None
        self._memory_store = None
        self._storage = None
        self._llm = None

    def _build_skill_aware_prompt(self) -> str:
        """Build prompt emphasizing skill-only approach."""
        available_skills = self._skills_tool._get_available_skills()
        skills_list = ", ".join(available_skills) if available_skills else "none yet"

        return f"""You are a trading agent that makes decisions PURELY based on learned skills.

You do NOT have access to technical analysis tools or complex indicators.
Your only source of trading knowledge is the skills that have been learned
from past competition data.

AVAILABLE SKILLS: {skills_list}

YOUR TOOLS:
- `trading_skills`: Read skill content for guidance
- `recommend_skill`: Get recommendation on which skill to check

DECISION PROCESS:
1. Check `trading_wisdom` for general guidance
2. Identify market regime (from context) and check `market-regimes`
3. Use `risk-management` for position sizing guidance
4. Make decision based on skill recommendations

IMPORTANT:
- You CANNOT calculate RSI, SMA, or other technical indicators
- You MUST rely on skill guidance
- If no relevant skill exists, be conservative (hold or small position)
- Always cite which skill informed your decision

CHARACTER:
{self.character or "A disciplined follower of learned wisdom."}

Trust the skills - they represent real statistical evidence from competition data."""

    def set_storage(self, storage: Any) -> None:
        """Set storage (minimal, just for compatibility)."""
        self._storage = storage
