"""Skill-Aware LLM Traders - Agents using learned skills with any OpenAI-compatible endpoint.

LLM versions of SkillAwareTrader and SkillOnlyTrader. Works with local inference
(LiteLLM, Ollama) and cloud providers via configurable base_url.
"""

from __future__ import annotations

import os
from typing import Any, Optional

from langchain_openai import ChatOpenAI

from agent_arena.agentic.base import AgenticTrader
from agent_arena.agentic.graph import create_trading_graph
from agent_arena.agentic.tools.skills import SkillRecommendationTool, TradingSkillsTool
from agent_arena.agents.model_registry import resolve_model
from agent_arena.core.agent import BaseAgent
from agent_arena.core.models import Decision


class SkillAwareLLMTrader(AgenticTrader):
    """
    Skill-aware trading agent using any OpenAI-compatible API endpoint.

    This agent extends AgenticTrader with:
    1. Access to skills generated by Observer Agent
    2. Skill-aware system prompt
    3. Tools for querying and applying skills

    Example config:
        config:
            model: gpt-oss-120b
            base_url: https://api.together.xyz/v1
            max_iterations: 4
            skills_dir: ".claude/skills"
            always_check_skills: true
    """

    def __init__(self, agent_id: str, name: str, config: Optional[dict] = None):
        config = config or {}
        super().__init__(agent_id, name, config)

        # Model configuration - default to gpt-oss-20b (best value)
        model_input = config.get("model", "gpt-oss-20b")
        self.model = resolve_model(model_input)

        # API configuration
        self.base_url = config.get("base_url", "https://api.together.xyz/v1")
        self.api_key_env = config.get("api_key_env", "TOGETHER_API_KEY")

        self.max_iterations = config.get("max_iterations", 4)

        # Token budget (reasoning models need headroom for thinking tokens)
        self.max_tokens = config.get("max_tokens", 2048)

        # Extra params for LLM (e.g. {think: false} for Ollama non-thinking)
        self.extra_params = config.get("extra_params", {})

        # Skills configuration
        self.skills_dir = config.get("skills_dir", ".claude/skills")
        self.always_check_skills = config.get("always_check_skills", True)

        # Initialize skills tools
        self._skills_tool = TradingSkillsTool(skills_dir=self.skills_dir)
        self._skill_recommend_tool = SkillRecommendationTool(skills_tool=self._skills_tool)

        # Add skills tools to the tool list (inherited tools + skills)
        self.tools.extend([
            self._skills_tool,
            self._skill_recommend_tool,
        ])

    async def on_start(self) -> None:
        """Initialize LLM and graph with skill-aware system prompt."""
        api_key = os.environ.get(self.api_key_env, "")

        # Use LangChain's OpenAI wrapper
        llm_kwargs: dict = {
            "model": self.model,
            "temperature": self.temperature,
            "max_tokens": self.max_tokens,
            "api_key": api_key,
            "base_url": self.base_url,
            "timeout": 120.0,
            "max_retries": 3,
        }
        if self.extra_params:
            llm_kwargs["model_kwargs"] = {"extra_body": self.extra_params}
        self._llm = ChatOpenAI(**llm_kwargs).bind_tools(self.tools)

        # Create the trading graph with skill-aware prompt
        self._graph = create_trading_graph(
            llm=self._llm,
            tools=self.tools,
            memory_store=self._memory_store,
            system_prompt=self._build_skill_aware_prompt(),
        )

    def _build_skill_aware_prompt(self) -> str:
        """Build system prompt that emphasizes skill usage."""
        available_skills = self._skills_tool._get_available_skills()
        skills_list = ", ".join(available_skills) if available_skills else "none yet"

        return f"""You are a sophisticated trading agent with access to LEARNED SKILLS.

Unlike basic traders, you can access institutional knowledge accumulated from
analyzing past competition data. This knowledge is stored in skills that you
should consult before making decisions.

AVAILABLE SKILLS: {skills_list}

HOW TO USE SKILLS:
1. Use `trading_skills` tool to read skill content
2. Use `recommend_skill` tool if unsure which skill is relevant
3. Apply the guidance from skills to your decision-making
4. Document which skills influenced your decision

DECISION WORKFLOW:
1. **Assess situation**: Analyze market data, portfolio state
2. **Apply tools**: Use technical analysis, risk calculator, etc. — form a complete, independent view first
3. **Consult skills (last resort only)**: Check a skill ONLY if live signals are genuinely ambiguous AND you have no other basis for a decision
   - For market analysis → check `market-regimes` only to *confirm* a view already supported by live data
   - For position sizing → check `risk-management` only to *cap or reduce* a size you already computed
   - For general guidance → check `trading-wisdom` only when all other signals are flat
4. **Make decision**: Live analysis drives the decision exclusively; skill guidance may only reduce size or add caution, NEVER increase conviction

SKILL PRIORITY:
- Skills are a *last-resort background hint* — live market data always takes precedence, no exceptions
- Treat every skill as potentially stale; assume it describes conditions that no longer exist
- If a skill suggests a trade that live data does not independently support, IGNORE the skill and HOLD
- If skill guidance conflicts with your live analysis in any way, discard the skill guidance entirely
- Default to hold unless live data alone (independent of any skill) justifies a trade
- When in doubt, hold — missing a trade is far cheaper than acting on a stale skill pattern
- Skipping the skill tools entirely is acceptable and often preferable

CHARACTER:
{self.character or "A disciplined trader who treats historical evidence as one input among many."}

Remember: Skills encode past patterns, but markets evolve. Validate skill guidance
against current conditions before acting. A skill that disagrees with live price
action should raise your skepticism, not override it."""

    async def decide(self, context: dict) -> Decision:
        """Make a skill-informed trading decision."""
        # Ensure graph is created
        if self._graph is None:
            await self.on_start()

        # Get decision from parent class
        decision = await super().decide(context)

        # Add skill-aware metadata
        decision.metadata["skill_aware"] = True
        decision.metadata["provider"] = "llm"
        decision.metadata["skills_available"] = self._skills_tool._get_available_skills()

        # Check if skills were used (look in tool results)
        tool_calls = decision.metadata.get("thoughts", [])
        skills_consulted = []
        for thought in tool_calls:
            if isinstance(thought, str):
                if "trading_skills" in thought.lower():
                    skills_consulted.append("trading_skills")
                if "recommend_skill" in thought.lower():
                    skills_consulted.append("recommend_skill")
        decision.metadata["skills_consulted"] = skills_consulted

        return decision


class SkillOnlyLLMTrader(BaseAgent):
    """
    Minimal skill-based trader using any OpenAI-compatible API endpoint.

    This agent ONLY uses skills, no other tools. Demonstrates pure
    skill-based trading without technical analysis tools.

    Example config:
        config:
            model: gpt-oss-120b
            base_url: https://api.together.xyz/v1
            max_iterations: 2
            skills_dir: ".claude/skills"
    """

    def __init__(self, agent_id: str, name: str, config: Optional[dict] = None):
        super().__init__(agent_id, name, config)
        config = config or {}

        # Model configuration - default to gpt-oss-20b (cheapest with good tools)
        model_input = config.get("model", "gpt-oss-20b")
        self.model = resolve_model(model_input)

        # API configuration
        self.base_url = config.get("base_url", "https://api.together.xyz/v1")
        self.api_key_env = config.get("api_key_env", "TOGETHER_API_KEY")

        self.max_iterations = config.get("max_iterations", 2)
        self.temperature = config.get("temperature", 0.5)
        self.max_tokens = config.get("max_tokens", 1024)
        self.character = config.get("character", "")
        self.skills_dir = config.get("skills_dir", ".claude/skills")
        self.always_check_skills = True

        # ONLY skills tools, nothing else
        self._skills_tool = TradingSkillsTool(skills_dir=self.skills_dir)
        self._skill_recommend_tool = SkillRecommendationTool(skills_tool=self._skills_tool)
        self.tools = [self._skills_tool, self._skill_recommend_tool]

        # Graph components
        self._graph = None
        self._memory_store = None
        self._storage = None
        self._llm = None

    def set_storage(self, storage: Any) -> None:
        """Set storage (minimal, just for compatibility)."""
        self._storage = storage

    async def on_start(self) -> None:
        """Initialize LLM and graph."""
        api_key = os.environ.get(self.api_key_env, "")

        # Use LangChain's OpenAI wrapper
        self._llm = ChatOpenAI(
            model=self.model,
            temperature=self.temperature,
            max_tokens=self.max_tokens,
            api_key=api_key,
            base_url=self.base_url,
            timeout=120.0,
            max_retries=1,
        ).bind_tools(self.tools)

        # Create the trading graph
        self._graph = create_trading_graph(
            llm=self._llm,
            tools=self.tools,
            memory_store=self._memory_store,
            system_prompt=self._build_skill_only_prompt(),
        )

    def _build_skill_only_prompt(self) -> str:
        """Build prompt emphasizing skill-only approach."""
        available_skills = self._skills_tool._get_available_skills()
        skills_list = ", ".join(available_skills) if available_skills else "none yet"

        return f"""You are a trading agent that makes decisions PURELY based on learned skills.

You do NOT have access to technical analysis tools or complex indicators.
Your only source of trading knowledge is the skills that have been learned
from past competition data.

AVAILABLE SKILLS: {skills_list}

YOUR TOOLS:
- `trading_skills`: Read skill content for guidance
- `recommend_skill`: Get recommendation on which skill to check

DECISION PROCESS:
1. Check `trading_wisdom` for general guidance
2. Identify market regime (from context) and check `market-regimes`
3. Use `risk-management` for position sizing guidance
4. Make decision based on skill recommendations

IMPORTANT:
- You CANNOT calculate RSI, SMA, or other technical indicators
- Use skill guidance as a very weak last-resort prior only — it encodes stale patterns that may no longer apply
- Treat every skill recommendation as "possibly outdated and possibly wrong"
- If skill guidance conflicts with current-market signals IN ANY WAY, discard the skill and hold
- If no relevant skill exists, default to hold
- If you consult a skill, always explicitly state whether current context confirmed OR contradicted it; if contradicted or ambiguous, do NOT act on the skill
- Defaulting to hold without consulting any skill at all is a perfectly valid decision

CHARACTER:
{self.character or "A disciplined trader who uses learned wisdom critically, not blindly."}

Skills encode historical patterns — treat them as informed hypotheses to test against
current conditions, not as rules to execute unconditionally."""

    async def decide(self, context: dict) -> Decision:
        """Make a skill-only trading decision."""
        from decimal import Decimal

        # Ensure graph is created
        if self._graph is None:
            await self.on_start()

        # Add agent_id to context for tools
        context["agent_id"] = self.agent_id

        # Build initial state
        from agent_arena.agentic.state import AgentState
        initial_state: AgentState = {
            "context": context,
            "agent_id": self.agent_id,
            "messages": [],
            "tool_calls": [],
            "tool_results": [],
            "thoughts": [],
            "iteration": 0,
            "max_iterations": self.max_iterations,
            "should_continue": True,
            "decision": None,
            "memories_retrieved": [],
        }

        try:
            from datetime import datetime, timezone
            start_time = datetime.now(timezone.utc)
            result = await self._graph.ainvoke(initial_state)
            latency = (datetime.now(timezone.utc) - start_time).total_seconds() * 1000

            # Extract decision
            decision_dict = result.get("decision", {})
            if not decision_dict:
                decision_dict = {"action": "hold", "reasoning": "No decision produced"}

            # Auto-calculate size when model chose to open but omitted size
            action = decision_dict.get("action", "hold")
            size_val = decision_dict.get("size")
            if action in ("open_long", "open_short") and not size_val:
                symbol = decision_dict.get("symbol")
                market = context.get("market", {})
                portfolio = context.get("portfolio", {})
                price = float(market.get(symbol, {}).get("price", 0))
                equity = float(portfolio.get("equity", 10000))
                if price > 0 and equity > 0:
                    conf = decision_dict.get("confidence", 0.3)
                    notional = equity * 0.10 * max(conf, 0.3)
                    size_val = notional / price
                    decision_dict["size"] = size_val

            decision = Decision(
                action=decision_dict.get("action", "hold"),
                symbol=decision_dict.get("symbol"),
                size=Decimal(str(decision_dict["size"])) if decision_dict.get("size") else None,
                leverage=decision_dict.get("leverage", 1),
                confidence=decision_dict.get("confidence", 0.3),
                reasoning=decision_dict.get("reasoning", ""),
                metadata={
                    "model": self.model,
                    "provider": "together",
                    "agent_type": "skill_only",
                    "iterations": result.get("iteration", 0),
                    "tool_calls_count": len(result.get("tool_results", [])),
                    "thoughts": result.get("thoughts", []),
                    "latency_ms": latency,
                    "skills_available": self._skills_tool._get_available_skills(),
                },
            )

            return decision

        except Exception as e:
            return Decision(
                action="hold",
                reasoning=f"Skill-only agent error: {str(e)}",
                confidence=0.0,
                metadata={
                    "error": str(e),
                    "agent_type": "skill_only",
                    "provider": "together",
                    "model": self.model,
                },
            )

    async def on_stop(self) -> None:
        """Cleanup on competition end."""
        pass
