"""Skills Tool - Allows agents to read and apply learned skills.

This tool provides trading agents access to skills generated by the
Observer Agent. Skills contain distilled knowledge from past competition
analysis.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional, Type

from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field


class SkillQueryInput(BaseModel):
    """Input for querying skills."""

    skill_name: Optional[str] = Field(
        default=None,
        description="Skill to read (e.g., 'trading-wisdom', 'market-regimes'). "
                   "If not provided, returns list of available skills.",
    )
    query: Optional[str] = Field(
        default=None,
        description="Optional query to filter skill content (e.g., 'trending market').",
    )


class TradingSkillsTool(BaseTool):
    """
    Tool for reading learned trading skills.

    Skills are SKILL.md files generated by the Observer Agent that contain:
    - Trading wisdom from past competitions
    - Market regime strategies
    - Risk management rules
    - Entry/exit signals

    Usage:
        # List available skills
        skills_tool.invoke({})

        # Read specific skill
        skills_tool.invoke({"skill_name": "trading-wisdom"})

        # Query for specific guidance
        skills_tool.invoke({"skill_name": "market-regimes", "query": "volatile"})
    """

    name: str = "trading_skills"
    description: str = (
        "Access learned trading knowledge from past competitions. "
        "WARNING: Skills encode historical patterns that may be stale or inapplicable to current conditions. "
        "Only consult this tool AFTER forming a complete independent view from live market data, "
        "and only to cap position size or add caution — never to initiate a trade. "
        "If live signals are clear, skip this tool entirely. "
        "Call without arguments to list available skills, or specify a skill name to read it."
    )
    args_schema: Type[BaseModel] = SkillQueryInput

    # Configuration
    skills_dir: Path = Path(".claude/skills")
    _skills_cache: dict = {}
    _cache_time: float = 0

    def __init__(self, skills_dir: str | Path = ".claude/skills", **kwargs: Any):
        super().__init__(**kwargs)
        self.skills_dir = Path(skills_dir)

    def set_context(self, context: dict) -> None:
        """Set context (not used by skills tool but required by interface)."""
        self._context = context

    def _run(
        self,
        skill_name: Optional[str] = None,
        query: Optional[str] = None,
    ) -> str:
        """Synchronous skill lookup."""
        return self._lookup_skill(skill_name, query)

    async def _arun(
        self,
        skill_name: Optional[str] = None,
        query: Optional[str] = None,
    ) -> str:
        """Async skill lookup."""
        return self._lookup_skill(skill_name, query)

    def _lookup_skill(
        self,
        skill_name: Optional[str],
        query: Optional[str],
    ) -> str:
        """Look up skill content."""
        # List skills if no name provided
        if not skill_name:
            return self._list_skills()

        # Read specific skill
        skill_content = self._read_skill(skill_name)
        if not skill_content:
            available = self._get_available_skills()
            return (
                f"Skill '{skill_name}' not found. "
                f"Available skills: {', '.join(available) if available else 'none'}"
            )

        # Filter by query if provided
        if query:
            skill_content = self._filter_by_query(skill_content, query)

        return skill_content

    def _list_skills(self) -> str:
        """List all available skills with descriptions."""
        skills = self._get_available_skills()
        if not skills:
            return (
                "No skills available yet. Skills are generated by the Observer Agent "
                "after analyzing competition data. Check back after the first daily analysis."
            )

        lines = ["## Available Trading Skills\n"]
        for skill_name in skills:
            meta = self._get_skill_meta(skill_name)
            desc = meta.get("description", "No description")
            updated = meta.get("last_updated", "Unknown")
            patterns = meta.get("pattern_count", 0)

            lines.append(f"### {skill_name}")
            lines.append(f"- **Description**: {desc[:100]}...")
            lines.append(f"- **Last updated**: {updated}")
            lines.append(f"- **Patterns**: {patterns}")
            lines.append("")

        lines.append("\nUse `skill_name` parameter to read a specific skill.")
        return "\n".join(lines)

    def _get_available_skills(self) -> list[str]:
        """Get list of available skill names."""
        skills = []
        if self.skills_dir.exists():
            for skill_dir in self.skills_dir.iterdir():
                if skill_dir.is_dir():
                    skill_file = skill_dir / "SKILL.md"
                    if skill_file.exists():
                        skills.append(skill_dir.name)
        return sorted(skills)

    def _read_skill(self, skill_name: str) -> Optional[str]:
        """Read a skill file."""
        skills_base = self.skills_dir.resolve()
        skill_file = (skills_base / skill_name / "SKILL.md").resolve()
        if not str(skill_file).startswith(str(skills_base)):
            return None
        if skill_file.exists():
            return skill_file.read_text()
        return None

    def _get_skill_meta(self, skill_name: str) -> dict:
        """Get skill metadata."""
        meta_file = self.skills_dir / skill_name / ".skill_meta.json"
        if meta_file.exists():
            try:
                return json.loads(meta_file.read_text())
            except json.JSONDecodeError:
                pass

        # Try to parse from SKILL.md frontmatter
        skill_content = self._read_skill(skill_name)
        if skill_content:
            return self._parse_frontmatter(skill_content)

        return {}

    def _parse_frontmatter(self, content: str) -> dict:
        """Parse YAML frontmatter from skill content."""
        meta = {}
        if content.startswith("---"):
            parts = content.split("---", 2)
            if len(parts) >= 3:
                import yaml
                try:
                    meta = yaml.safe_load(parts[1]) or {}
                except Exception:
                    # Parse manually
                    for line in parts[1].strip().split("\n"):
                        if ":" in line:
                            key, value = line.split(":", 1)
                            meta[key.strip()] = value.strip()
        return meta

    def _filter_by_query(self, content: str, query: str) -> str:
        """Filter skill content by query."""
        query_lower = query.lower()
        lines = content.split("\n")

        # Find relevant sections
        relevant_lines = []
        in_relevant_section = False
        current_section = []

        for line in lines:
            # Track section headers
            if line.startswith("## ") or line.startswith("### "):
                # Save previous section if relevant
                if in_relevant_section and current_section:
                    relevant_lines.extend(current_section)
                    relevant_lines.append("")

                current_section = [line]
                # Check if section header matches query
                in_relevant_section = query_lower in line.lower()
            else:
                current_section.append(line)
                # Check if line contains query
                if query_lower in line.lower():
                    in_relevant_section = True

        # Don't forget last section
        if in_relevant_section and current_section:
            relevant_lines.extend(current_section)

        if relevant_lines:
            return f"## Filtered results for '{query}':\n\n" + "\n".join(relevant_lines)
        else:
            return f"No match for '{query}'. Full content:\n\n{content[:2000]}..."


class SkillRecommendationTool(BaseTool):
    """
    Tool that recommends which skill to consult based on context.

    This tool analyzes the current market situation and suggests
    which skills would be most relevant to consult.
    """

    name: str = "recommend_skill"
    description: str = (
        "Get a recommendation on which trading skill to consult based on "
        "the current market context. Useful when you're unsure which skill "
        "would provide the most relevant guidance."
    )

    # Reference to skills tool
    skills_tool: Optional[TradingSkillsTool] = None

    def __init__(self, skills_tool: Optional[TradingSkillsTool] = None, **kwargs: Any):
        super().__init__(**kwargs)
        self.skills_tool = skills_tool or TradingSkillsTool()

    def set_context(self, context: dict) -> None:
        """Set context (not used by this tool but required by interface)."""
        self._context = context

    def _run(self, context: str = "") -> str:
        """Recommend skills based on context."""
        return self._recommend(context)

    async def _arun(self, context: str = "") -> str:
        """Async recommendation."""
        return self._recommend(context)

    def _recommend(self, context: str) -> str:
        """Generate skill recommendation."""
        context_lower = context.lower()
        recommendations = []

        # Check for keywords and map to skills
        keyword_skill_map = {
            # Market regime keywords
            ("volatile", "volatility", "swing", "uncertain"): "market-regimes",
            ("trending", "trend", "bull", "bear", "momentum"): "market-regimes",
            ("ranging", "sideways", "consolidation"): "market-regimes",

            # Risk keywords
            ("risk", "position size", "stop", "loss", "drawdown"): "risk-management",
            ("leverage", "margin", "liquidation"): "risk-management",

            # Entry/exit keywords
            ("entry", "enter", "open", "buy", "long", "short"): "entry-signals",
            ("exit", "close", "sell", "take profit"): "exit-signals",

            # General
            ("strategy", "approach", "what should", "how to"): "trading-wisdom",
        }

        for keywords, skill in keyword_skill_map.items():
            if any(kw in context_lower for kw in keywords):
                if skill not in recommendations:
                    recommendations.append(skill)

        # Default recommendation
        if not recommendations:
            recommendations = ["trading-wisdom"]

        # Format response
        available = self.skills_tool._get_available_skills() if self.skills_tool else []

        lines = ["## Skill Recommendations\n"]
        lines.append(f"Based on context: *{context[:100]}...*\n")

        for skill in recommendations:
            if skill in available:
                lines.append(f"- **{skill}** - Available, recommended for your query")
            else:
                lines.append(f"- **{skill}** - Not yet generated (no data)")

        lines.append("\nUse the `trading_skills` tool with the skill name to read it.")

        return "\n".join(lines)
