"""EvoSkill Validator — A/B tests proposed skills via backtest and promotes winners."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

from agent_arena.reflexion.clustering import FailureCluster

logger = logging.getLogger(__name__)


@dataclass
class SkillValidationResult:
    """Result of an A/B skill validation."""

    cluster_id: int
    skill_name: str
    treatment_fitness: float = 0.0
    control_fitness: float = 0.0
    improvement_pct: float = 0.0
    promoted: bool = False


class EvoSkillValidator:
    """A/B tests proposed skills from failure clusters.

    For each proposed skill:
    1. Runs backtest with skill (treatment) vs without (control)
    2. If improvement > threshold → writes SKILL.md to .claude/skills/
    3. Tracks lifecycle in skill_proposals table
    """

    def __init__(
        self,
        storage: Any,
        skills_dir: str = ".claude/skills",
        improvement_threshold: float = 0.05,
    ):
        self.storage = storage
        self.skills_dir = Path(skills_dir)
        self.improvement_threshold = improvement_threshold

    async def validate_and_promote(
        self,
        clusters: list[FailureCluster],
    ) -> list[SkillValidationResult]:
        """Validate proposed skills from failure clusters.

        For now, uses a simplified validation that checks if the proposed
        skill is substantive enough to promote. Full A/B backtesting
        requires the backtest infrastructure to be running.
        """
        results = []

        for cluster in clusters:
            if not cluster.proposed_skill:
                continue

            result = await self._validate_skill(cluster)
            if result:
                results.append(result)

        return results

    async def _validate_skill(
        self, cluster: FailureCluster,
    ) -> Optional[SkillValidationResult]:
        """Validate a single proposed skill.

        In the full implementation, this runs parallel backtests with
        and without the skill. For now, we use a heuristic: promote if
        the cluster has enough evidence (sample_size >= 5).
        """
        skill_name = self._derive_skill_name(cluster)

        # Check if this skill already exists
        skill_path = self.skills_dir / skill_name / "SKILL.md"
        if skill_path.exists():
            logger.info("Skill %s already exists, skipping", skill_name)
            return None

        # Heuristic validation: promote if sufficient evidence
        # In production, this would run actual A/B backtests
        is_promoted = cluster.sample_size >= 5 and len(cluster.proposed_skill) > 20

        result = SkillValidationResult(
            cluster_id=0,  # Set after save
            skill_name=skill_name,
            treatment_fitness=0.0,  # Placeholder for actual backtest
            control_fitness=0.0,
            improvement_pct=0.0,
            promoted=is_promoted,
        )

        if is_promoted:
            self._write_skill(skill_name, cluster)
            logger.info(
                "Promoted skill '%s' from failure cluster '%s' (%d trades)",
                skill_name, cluster.cluster_label, cluster.sample_size,
            )

        # Save proposal to DB
        await self._save_proposal(cluster, result)

        return result

    def _derive_skill_name(self, cluster: FailureCluster) -> str:
        """Derive a skill directory name from a cluster label."""
        # Convert "High Confidence Reversal Failures" → "high-confidence-reversal-failures"
        name = cluster.cluster_label.lower()
        name = "".join(c if c.isalnum() or c == " " else "" for c in name)
        name = name.strip().replace(" ", "-")[:50]
        return f"evolved-{name}" if name else "evolved-unknown"

    def _write_skill(self, skill_name: str, cluster: FailureCluster) -> None:
        """Write a SKILL.md file for a promoted skill."""
        skill_dir = self.skills_dir / skill_name
        skill_dir.mkdir(parents=True, exist_ok=True)

        content = f"""# {cluster.cluster_label}

**Source**: Auto-generated by EvoSkill from failure cluster analysis
**Regime**: {cluster.regime or 'All'}
**Evidence**: {cluster.sample_size} losing trades analyzed

## Failure Pattern

{cluster.failure_mode}

## Rule

{cluster.proposed_skill}

---
*Auto-generated. Validate with live trading results before relying on this rule.*
"""

        skill_path = skill_dir / "SKILL.md"
        skill_path.write_text(content)

    async def _save_proposal(
        self, cluster: FailureCluster, result: SkillValidationResult,
    ) -> None:
        """Save a skill proposal to the database."""
        if not hasattr(self.storage, "pool"):
            return

        try:
            async with self.storage.pool.acquire() as conn:
                status = "promoted" if result.promoted else "proposed"
                await conn.execute(
                    """
                    INSERT INTO skill_proposals (
                        skill_name, skill_content,
                        treatment_fitness, control_fitness,
                        improvement_pct, status
                    ) VALUES ($1, $2, $3, $4, $5, $6)
                    """,
                    result.skill_name,
                    cluster.proposed_skill,
                    result.treatment_fitness,
                    result.control_fitness,
                    result.improvement_pct,
                    status,
                )
        except Exception:
            logger.exception("Failed to save skill proposal")

    async def prune_underperformers(self, max_age_days: int = 30) -> int:
        """Remove promoted skills that haven't improved performance.

        Checks skill_proposals table for promoted skills older than
        max_age_days that show no improvement in agent performance.
        Returns count of pruned skills.
        """
        # Placeholder — full implementation would check live performance
        # metrics against the pre-skill baseline
        return 0
